# references:
# * http://www.objc.io/issue-6/travis-ci.html
osx_image: xcode7.2
language: objective-c

install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - pod install --project-directory=Xcode/Testing-pod
  - pod install --project-directory=Xcode/Testing-swift
  - xctool -workspace Xcode/Testing-pod/XMPPFrameworkTests.xcworkspace -scheme XMPPFrameworkTests -sdk iphonesimulator -arch i386 test
  #- xctool -workspace Xcode/Testing-swift/XMPPSwift.xcworkspace -scheme XMPPSwift -sdk iphonesimulator -arch i386 test
  - set -o pipefail && xcodebuild test -workspace Xcode/Testing-swift/XMPPSwift.xcworkspace  -scheme XMPPSwift -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2' | xcpretty -c
